newSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityTopic]
      target: [formBottom]
      is_component: true

editSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityTopic]
      target: [formBottom]
      is_component: true