newSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityEvent]
      target: [lastRow]
      is_component: true

editSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityEvent]
      target: [lastRow]
      is_component: true

showSuccess:
  customize:
    tagForm:
      template: [tag, show]
      parts: [communityEvent]
      target: [lastRow]
      is_component: true