<?php

/**
 * PluginTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opTagPlugin
 * @subpackage model
 * @author     Hiromi Hishida<info@77-web.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginTag extends BaseTag
{
  protected $foreignObject = null;

  public function getForeignObject()
  {
    if($this->foreignObject) return $this->foreignObject;
    
    $obj = Doctrine::getTable($this->getForeignTable())->find($this->getForeignId());
    if($obj)
    {
      $this->foreignObject = $obj;
      return $this->foreignObject;
    }
    return null;
  }
  
  public function getForeignTitle()
  {
    $key = "name";
    if($this->getForeignTable()=="Diary")
    {
      $key = "title";
    }
    return $this->getForeignObject()->get($key);
  }
  
  public function getForeignUrl()
  {
    $url = "";
    switch($this->getForeignTable())
    {
      case "Diary":
        $url = "diary/show?id=".$this->getForeignId();
        break;
      case "CommunityTopic":
        $url = "communityTopic/show?id=".$this->getForeignId();
        break;
      case "CommunityEvent":
        $url = "communityEvent/show?id=".$this->getForeignId();
        break;
    }
    return $url;
  }
  
  public function getForeignDate()
  {
    return $this->getForeignObject()->getCreatedAt();
  }
}