<?php
/**
 * PluginTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opTagPlugin
 * @subpackage lib
 * @author     Hiromi Hishida<info@77-web.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class opTagRemover
{
  public static function listenToDiaryDelete($args)
  {
    $obj = $args['actionInstance']->getVar("diary");
    self::removeTags($obj);
  }
  
  public static function listenToCommunityEventDelete($args)
  {
    $obj = $args['actionInstance']->getVar("communityEvent");
    self::removeTags($obj);
  }
  
  public static function listenToCommunityTopicDelete($args)
  {
    $obj = $args['actionInstance']->getVar("communityTopic");
    self::removeTags($obj);
  }
  
  public static function removeTags($obj)
  {
    foreach(Doctrine::getTable("Tag")->getTags($obj->getId(), get_class($obj)) as $tag)
    {
      $tag->delete();
    }
  }
}