newSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityEvent]
      target: [formBottom]
      is_component: true

editSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityEvent]
      target: [formBottom]
      is_component: true