newSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityTopic]
      target: [lastRow]
      is_component: true

editSuccess:
  customize:
    tagForm:
      template: [tag, form]
      parts: [formCommunityTopic]
      target: [lastRow]
      is_component: true

showSuccess:
  customize:
    tagShow:
      template: [tag, show]
      parts: [topicDetailBox]
      target: [top]
      is_component: true